package project.code_analysis.tweet_ql;

import project.code_analysis.core.ISyntaxKind;

/**
 * ProjectSouthernCross
 * <p>
 * Created by Dy.Zhao on 2016/8/11.
 */
public enum TweetQlSyntaxTokenKind implements ISyntaxKind {
    //region SyntaxTokenKind
    CREATE_KEYWORD_TOKEN,
    SELECT_KEYWORD_TOKEN,
    FROM_KEYWORD_TOKEN,
    WHERE_KEYWORD_TOKEN,
    CONTAIN_KEYWORD_TOKEN,
    LIKE_KEYWORD_TOKEN,
    AND_KEYWORD_TOKEN,
    OR_KEYWORD_TOKEN,
    NOT_KEYWORD_TOKEN,
    SKIP_KEYWORD_TOKEN,
    WINDOW_KEYWORD_TOKEN,
    AS_KEYWORD_TOKEN,
    BETWEEN_KEYWORD_TOKEN,
    ORDER_KEYWORD_TOKEN,
    BY_KEYWORD_TOKEN,
    ASCEND_KEYWORD_TOKEN,
    DESCEND_KEYWORD_TOKEN,

    OPEN_PARENTHESES_TOKEN,
    CLOSE_PARENTHESES_TOKEN,
    OPEN_BRACKET_TOKEN,
    CLOSE_BRACKET_TOKEN,
    OPEN_BRACE_TOKEN,
    CLOSE_BRACE_TOKEN,

    COMMA_TOKEN,
    DOT_TOKEN,
    COLON_TOKEN,
    SEMICOLON_TOKEN,

    EQUAL_TOKEN,
    BIGGER_TOKEN,
    LESS_TOKEN,
    BIGGER_EQUAL_TOKEN,
    LESS_EQUAL_TOKEN,

    CRLF_TOKEN,
    LF_TOKEN,

    STAR_TOKEN,

    DIGIT_TOKEN,

    IDENTIFIER_TOKEN,
    LITERAL_STRING_TOKEN,

    //endregion


}
